apiVersion: v1
kind: Service
metadata:
  name: symphony
  labels:
    app: symphony
spec:
  selector:
    app: symphony
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
