apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: symphony
  namespace: {{ .Release.Namespace }}
spec:
  network:
    serviceMesh:
      mode: ambient
    expose:
      - service: symphony
        selector:
          app: symphony
        gateway: tenant
        host: symphony
        port: {{ .Values.service.port }}
        uptime:
          checks:
            paths:
              - /
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace
      {{- with .Values.additionalNetworkAllow }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
