# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release Container & Charts

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/release-container-and-charts.yaml"

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  packages: read # Allows reading the content of the repository's packages.
  id-token: write

jobs:
  publish:
    runs-on: appstore-4-core-amd64
    permissions:
      contents: write # Allows writing the content of the repository.
      packages: write # Allows writing the content of the repository's packages.
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Get Container Version
        id: get_version
        run: |
          VERSION=$(yq '.flavors[] | select(.name == "upstream") | .version | split("-") | .[0]' releaser.yaml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Build and Push Container Image
        run: |
          CONTAINER_PATH="src"
          IMAGE_ID=ghcr.io/uds-packages/reference-package/container/reference-package

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag $IMAGE_ID:${{ env.VERSION }} \
            --tag $IMAGE_ID:latest \
            --file $CONTAINER_PATH/Dockerfile \
            $CONTAINER_PATH
